version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Hello world"
      - run: echo ${CIRCLE_REPOSITORY_URL} # Built-in environment variable is printed
      - run: echo ${AWS_SECRET_ACCESS_KEY} # Project environment variable is masked
workflows:
  build:
    jobs:
      - build
